### ISSUE TITLE
FYI: repurposed to program ATtiny28 via ATmega4809 (on protoboard.)

### ISSUE THREAD

**Issue by WestfW** [dilshan/avr-hv2#2]
(no, this isn't really an "issue.")

It happens that I have some ATtiny28 chips that I want to program.
These are only programmable via HVPP, and my STK500 doesn't seem to be working, so I looked around for something else that might be able to program it, and found your avr-hv2 project.

I based the hardware (built on a protoboard) on your project, plus the datasheet, plus some other HV programmers, and started with your firmware.  I don't think that much of it is left - the ATtiny28 works somewhat differently, I didn't try to make it more general, I used an ATmega4809 board as the programmer, and I implemented a more user-oriented communications protocol, but I wanted to thank you for publishing your project, since it was definitely easier to start working with it than to start from nothing...

Should you need to program a very old HVPP chip, it might be useful to look at.  It's here:  https://github.com/WestfW/Duino-hacks/tree/master/hvTiny28prog

Thanks!

**Comment by dilshan** [comment]
Hello @WestfW. 

Thank you for share this information.

I had limited experience with the ATTiny family because it is not much popular here (in _Sri Lanka_). At the time of this development, ATTiny chips are hard to find in the market. That's the main reason I skip ATTiny support. 

It's good to have HVPP support programmer firmware for the ATTiny family. Most of the time, I need these HVPPs to recover the chips, which got "bricked" by wrong fuse settings. 

Thank you! :+1:
